% pi1：pi1 の固定的な通信候補を作る。

function profile = pi1()
    % 空のプロファイルを作り、name を "pi1" にする。
    profile.name = "pi1";
    % 状態入力候補として、利用可能な ROS 経路を名前付きで加える。
    % 各候補には方式、トピックまたはポート、型、位置か速度かを書く。
    % 状態入力は /pi1/odometry/<入力名> に揃え、指令は /pi1/rover_drive に送る。
    profile.odometrySources.motive = struct( ...
        'protocol', "ros", 'kind', "position", ...
        'topic', "/pi1/odometry/motive", ...
        'messageType', "nav_msgs/Odometry");
    profile.odometrySources.otos = struct( ...
        'protocol', "ros", 'kind', "position", ...
        'topic', "/pi1/odometry/otos", ...
        'messageType', "geometry_msgs/Pose2D");
    profile.odometrySources.wheelOdometry = struct( ...
        'protocol', "ros", 'kind', "velocity", ...
        'topic', "/pi1/odometry/wheel", ...
        'messageType', "nav_msgs/Odometry");
    % 剛体の名前は保持し、Streaming ID は起動時に Motive から照合する。
    profile.motive = struct('name', "pi1", 'id', NaN);
    % 指令先候補にも方式とトピックまたは宛先を名前付きで加える。
    profile.commandSinks.rosDrive = struct( ...
        'protocol', "ros", 'topic', "/pi1/rover_drive");
    % 今回使う候補や Motive 剛体、初期位置は選ばず、プロファイルを返す。
end
