% pi2：pi2 の固定的な通信候補を作る。

function profile = pi2()
    % 空のプロファイルを作り、name を "pi2" にする。
    profile.name = "pi2";
    % 状態入力候補として、利用可能な ROS 経路を名前付きで加える。
    % 各候補には方式、トピックまたはポート、型、位置か速度かを書く。
    % 状態入力は /pi2/odometry/<入力名> に揃え、指令は /pi2/rover_drive に送る。
    profile.odometrySources.motive = struct( ...
        'protocol', "ros", 'kind', "position", ...
        'topic', "/pi2/odometry/motive", ...
        'messageType', "nav_msgs/Odometry");
    profile.odometrySources.otos = struct( ...
        'protocol', "ros", 'kind', "position", ...
        'topic', "/pi2/odometry/otos", ...
        'messageType', "geometry_msgs/Pose2D");
    profile.odometrySources.wheelOdometry = struct( ...
        'protocol', "ros", 'kind', "velocity", ...
        'topic', "/pi2/odometry/wheel", ...
        'messageType', "nav_msgs/Odometry");
    profile.motive = struct('name', "pi2", 'id', NaN);
    % 指令先候補にも方式とトピックまたは宛先を名前付きで加える。
    profile.commandSinks.rosDrive = struct( ...
        'protocol', "ros", 'topic', "/pi2/rover_drive");
    % 今回使う候補や Motive 剛体、初期位置は選ばず、プロファイルを返す。
end
