% experimentConfig：今回の実験を表す設定を作る。

function config = experimentConfig()
    % 空の実験設定を作り、今回使う車両名を順序付きで並べる。
    % config.selectedVehicleNames = ["pi1", "pi2", "pi3"];
    config.selectedVehicleNames = ["pi3"];
    % 全車両を止める制御則を初期値として選ぶ。
    % config.controller = @station.stopController;
    % マウス操作へ切り替える場合は上の一行をコメントアウトし、次を使う。
    manual = station.MouseController(0.05, 0.2);
    config.controller = @(vehicles) manual.commands(vehicles);
    config.cleanupController = @() manual.close();
    % 選んだ各車両について、同じ名前の設定欄を一つずつ作る。
    % その車両が今回使う状態入力候補と指令先候補の名前を書く。
    % 初期位置を [x, y, theta] の順に m、m、rad で書く。
    % 状態入力ごとの座標の扱いは odometrySource から自動的に決まる。
    % 新しい車両の設定は、次の形をコピーして車両名と全項目を明示する。
    % config.vehicleSettings.<車両名> = struct( ...
    %     'odometrySource', "motive", ...
    %     'commandSink', "rosDrive", ...
    %     'initialState', [0 0 0]);
    config.vehicleSettings = struct();
    config.vehicleSettings.pi1 = struct( ...
        'odometrySource', "motive", ...
        'commandSink', "rosDrive", ...
        'initialState', [0 0 0]);
    config.vehicleSettings.pi2 = struct( ...
        'odometrySource', "motive", ...
        'commandSink', "rosDrive", ...
        'initialState', [1 0 0]);
    config.vehicleSettings.pi3 = struct( ...
        'odometrySource', "otos", ...
        'commandSink', "rosDrive", ...
        'initialState', [-1 0 0]);
    config.vehicleSettings.katchaka = struct( ...
        'odometrySource', "udpVelocity", ...
        'commandSink', "udpDrive", ...
        'initialState', [2 0 0]);
    % 車両やネットワークへは接続せず、設定だけを返す。
end
