% resolveVehicleSettings：今回使う車両設定を確定する。

function settings = resolveVehicleSettings(catalog, experiment, station, mode, selectedNames)
    % 登録表、実験設定、PC 設定、mode と任意の vehicleNames 指定を受け取る。
    % vehicleNames 指定があればそれを、なければ実験設定の車両一覧を使う。
    if nargin < 5 || isempty(selectedNames)
        selectedNames = experiment.selectedVehicleNames;
    end
    names = string(selectedNames(:).');
    % 一覧が空、重複している、登録表にない名前を含む場合は終了する。
    assert(~isempty(names) && all(strlength(names) > 0), ...
        'Station:NoVehicles', 'Select at least one vehicle.');
    assert(numel(unique(names)) == numel(names), ...
        'Station:DuplicateVehicle', 'Selected vehicle names must be unique.');
    assert(ismember(string(mode), ["simulation", "experiment", "bridge"]), ...
        'Station:InvalidMode', 'Unknown run mode.');
    validateStationNumbers(station);

    settings = repmat(struct('name', "", 'odometrySource', "", 'odometryInput', struct(), ...
        'commandSink', "", 'commandOutput', struct(), 'initialState', zeros(1,3), ...
        'motive', struct('name', "", 'id', NaN)), ...
        1, numel(names));
    usedPorts = [];
    usedOdometryTopics = strings(0,1);
    usedCommandTopics = strings(0,1);
    motiveIds = [];
    motiveNames = strings(0,1);
    % 選択順に車両を一台ずつ取り出す。
    % 登録表からその車両のプロファイルを取得する。
    for index = 1:numel(names)
        name = names(index);
        assert(isvarname(char(name)) && isfield(catalog, char(name)), ...
            'Station:UnknownVehicle', 'Vehicle %s is not registered.', name);
        assert(isfield(experiment.vehicleSettings, char(name)), ...
            'Station:MissingVehicleSettings', 'No experiment settings for %s.', name);
        profile = catalog.(char(name));
        selection = experiment.vehicleSettings.(char(name));
        required = {'odometrySource', 'commandSink', 'initialState'};
        assert(all(isfield(selection, required)), 'Station:InvalidSettings', ...
            'Settings for %s are missing a required field.', name);
        assert(~isfield(selection, 'coordinateMode'), ...
            'Station:ObsoleteCoordinateMode', ...
            'Remove coordinateMode for %s; odometrySource determines coordinates.', name);
        % 実験設定に書かれた状態入力候補と指令先候補を探す。
        % どちらかが見つからなければ、車両名と候補名を示して終了する。
        sourceKey = string(selection.odometrySource);
        sinkKey = string(selection.commandSink);
        assert(isscalar(sourceKey) && isfield(profile.odometrySources, char(sourceKey)), ...
            'Station:UnknownSource', 'Unknown odometry source %s for %s.', sourceKey, name);
        assert(isscalar(sinkKey) && isfield(profile.commandSinks, char(sinkKey)), ...
            'Station:UnknownSink', 'Unknown command sink %s for %s.', sinkKey, name);
        source = profile.odometrySources.(char(sourceKey));
        sink = profile.commandSinks.(char(sinkKey));
        % 選んだ接続情報に、今回の初期位置を重ねる。
        % 初期位置、数値、トピック、必要な IP とポートを調べる。
        initialState = double(selection.initialState);
        assert(isnumeric(selection.initialState) && isreal(initialState) && ...
            isequal(size(initialState), [1 3]) && all(isfinite(initialState)), ...
            'Station:InvalidInitialState', ...
            'Initial state for %s must be [x y theta].', name);
        assert(isfield(source, 'kind') && ismember(string(source.kind), ["position", "velocity"]), ...
            'Station:InvalidSource', 'Invalid odometry kind for %s.', name);
        % 位置入力の座標解釈は入力名から一意に決める。未知の位置入力は
        % 暗黙にどちらかの座標系とみなさず、追加時に明示的に対応させる。
        assert(string(source.kind) ~= "position" || ...
            ismember(sourceKey, ["motive", "otos"]), ...
            'Station:UnknownSourceSemantics', ...
            'Coordinate semantics are not defined for %s.', sourceKey);
        assert(sourceKey ~= "otos" || string(source.kind) == "position", ...
            'Station:InvalidSource', 'OTOS must supply position for %s.', name);
        if isfield(profile, 'motive')
            motive = profile.motive;
        else
            motive = struct('name', "", 'id', NaN);
        end
        assert(isstruct(motive) && isscalar(motive) && ...
            isfield(motive, 'name') && isfield(motive, 'id'), ...
            'Station:InvalidMotiveMapping', 'Invalid Motive mapping for %s.', name);
        motive.name = string(motive.name);
        motive.id = double(motive.id);
        assert(isscalar(motive.name) && isscalar(motive.id) && ...
            (isnan(motive.id) || (isfinite(motive.id) && motive.id >= 0 && ...
            fix(motive.id) == motive.id)), 'Station:InvalidMotiveMapping', ...
            'Invalid Motive ID for %s.', name);
        % 剛体対応はプロファイルに保持する。今回 Motive を選んだときだけ必要性と重複を調べる。
        if sourceKey == "motive"
            assert(string(source.protocol) == "ros" && string(source.kind) == "position" && ...
                (strlength(motive.name) > 0 || ~isnan(motive.id)), ...
                'Station:InvalidMotiveMapping', 'Motive mapping is missing for %s.', name);
            if ~isnan(motive.id), motiveIds(end+1) = motive.id; end %#ok<AGROW>
            if strlength(motive.name) > 0, motiveNames(end+1) = motive.name; end %#ok<AGROW>
        end
        source.protocol = string(source.protocol);
        sink.protocol = string(sink.protocol);
        assert(ismember(source.protocol, ["ros", "udp"]) && ...
            ismember(sink.protocol, ["ros", "udp"]), ...
            'Station:InvalidTransport', 'Unknown transport for %s.', name);
        if source.protocol == "ros"
            validateTopic(source.topic, name);
            assert(isfield(source, 'messageType') && ...
                (source.kind == "position" && ismember(string(source.messageType), ...
                    ["nav_msgs/Odometry", "geometry_msgs/Pose2D"]) || ...
                 source.kind == "velocity" && ismember(string(source.messageType), ...
                    ["nav_msgs/Odometry", "geometry_msgs/Twist"])), ...
                'Station:InvalidSource', 'Message type cannot supply odometry for %s.', name);
            usedOdometryTopics(end+1) = string(source.topic); %#ok<AGROW>
        else
            validatePort(source.localPort, name);
            usedPorts(end+1) = double(source.localPort); %#ok<AGROW>
        end
        if sink.protocol == "ros"
            validateTopic(sink.topic, name);
            usedCommandTopics(end+1) = string(sink.topic); %#ok<AGROW>
        else
            validatePort(sink.localPort, name);
            validatePort(sink.targetPort, name);
            usedPorts(end+1) = double(sink.localPort); %#ok<AGROW>
            % simulation のときは実機接続先 IP が空でも通し、通信資源は開かない。
            % experiment のときは選んだ経路に必要な接続先だけを必須とする。
            if string(mode) == "experiment"
                assert(strlength(string(sink.targetIp)) > 0, ...
                    'Station:MissingAddress', 'Target IP for %s is empty.', name);
            end
        end
        settings(index) = struct('name', name, 'odometrySource', sourceKey, ...
            'odometryInput', source, 'commandSink', sinkKey, ...
            'commandOutput', sink, 'initialState', initialState, 'motive', motive);
    end
    % 全台分を作ってから、ローカルポート、配信トピック、剛体対応の重複を調べる。
    % 一つでも不正なら何も返さず、該当する車両名と項目を示して終了する。
    assert(numel(unique(usedPorts)) == numel(usedPorts), ...
        'Station:DuplicatePort', 'Selected vehicles reuse a local UDP port.');
    assert(numel(unique(usedOdometryTopics)) == numel(usedOdometryTopics), ...
        'Station:DuplicateTopic', 'Selected vehicles reuse an odometry topic.');
    assert(numel(unique(usedCommandTopics)) == numel(usedCommandTopics), ...
        'Station:DuplicateTopic', 'Selected vehicles reuse a command topic.');
    assert(numel(unique(motiveIds)) == numel(motiveIds) && ...
        numel(unique(motiveNames)) == numel(motiveNames), ...
        'Station:DuplicateMapping', 'Selected vehicles reuse a Motive mapping.');
    if string(mode) == "experiment" || string(mode) == "bridge"
        if any(arrayfun(@(s) s.odometryInput.protocol == "ros" || ...
                s.commandOutput.protocol == "ros", settings)) || string(mode) == "bridge"
            assert(strlength(string(station.ros.masterUri)) > 0 && ...
                strlength(string(station.ros.nodeHost)) > 0, ...
                'Station:MissingRosAddress', 'Set ROS masterUri and nodeHost.');
        end
    end
    if string(mode) == "bridge"
        assert(strlength(string(station.motive.serverIp)) > 0 && ...
            strlength(string(station.motive.clientIp)) > 0, ...
            'Motive:MissingAddress', 'Set Motive serverIp and clientIp.');
        validateattributes(station.motive.pollRateHz, {'numeric'}, ...
            {'scalar', 'real', 'finite', 'positive'}, mfilename, 'motive.pollRateHz');
        assert(ismember(string(station.motive.connectionType), ...
            ["Unicast", "Multicast"]) && ...
            strlength(string(station.motive.frameId)) > 0, ...
            'Motive:InvalidConfig', ...
            'Set Motive connectionType and frameId.');
    end
    % 問題がなければ、選択順の確定済み車両設定を返す。
    % runControlStation と runMotiveRosBridge はこの同じ手順で設定を作る。
    % 起動間に設定が編集され得るため、表示された確定値を照合する。
end

function validateStationNumbers(config)
    fields = ["controlRateHz", "durationSeconds", "connectionTimeoutSeconds", ...
        "odometryTimeoutSeconds", "maxLinearVelocity", "maxAngularVelocity"];
    for field = fields
        assert(isfield(config, char(field)), 'Station:InvalidConfig', ...
            'Missing station setting %s.', field);
        validateattributes(config.(field), {'numeric'}, ...
            {'scalar', 'real', 'finite', 'positive'}, mfilename, char(field));
    end
    assert(isfield(config, 'logDirectory') && ...
        strlength(string(config.logDirectory)) > 0, ...
        'Station:InvalidConfig', 'logDirectory is required.');
end

function validateTopic(topic, name)
    topic = string(topic);
    assert(isscalar(topic) && strlength(topic) > 1 && startsWith(topic, "/") && ...
        isempty(regexp(char(topic), '[^a-zA-Z0-9_/]', 'once')), ...
        'Station:InvalidTopic', 'Invalid ROS topic for %s.', name);
end

function validatePort(port, name)
    assert(isnumeric(port) && isscalar(port) && isfinite(port) && ...
        port >= 1 && port <= 65535 && fix(port) == port, ...
        'Station:InvalidPort', 'Invalid UDP port for %s.', name);
end
