% vehicleCatalog：車両プロファイルを自動登録し、名前と ROS グループを検査する。

function catalog = vehicleCatalog()
    catalog = struct();
    root = fileparts(fileparts(mfilename('fullpath')));
    files = dir(fullfile(root, '+vehicleProfiles', '*.m'));
    assert(~isempty(files), 'Station:InvalidCatalog', ...
        'No vehicle profile files were found.');
    [~, order] = sort(string({files.name}));
    files = files(order);
    for fileIndex = 1:numel(files)
        % ファイル名から関数を呼び、明示された車両名との一致を確認する。
        [~, fileName] = fileparts(files(fileIndex).name);
        assert(isvarname(fileName), 'Station:InvalidCatalog', ...
            'Invalid vehicle profile file name: %s.', files(fileIndex).name);
        profile = feval(str2func(['vehicleProfiles.' fileName]));
        assert(isstruct(profile) && isscalar(profile) && isfield(profile, 'name'), ...
            'Station:InvalidCatalog', ...
            'Vehicle profile %s must define one profile with a name.', fileName);
        name = string(profile.name);
        assert(isscalar(name) && name == string(fileName), ...
            'Station:InvalidCatalog', ...
            'Profile name must match file name %s.', fileName);
        assert(~isfield(catalog, fileName), 'Station:DuplicateVehicle', ...
            'Vehicle profile %s is registered twice.', fileName);
        assert(isfield(profile, 'odometrySources') && ...
            isstruct(profile.odometrySources) && ...
            ~isempty(fieldnames(profile.odometrySources)) && ...
            isfield(profile, 'commandSinks') && ...
            isstruct(profile.commandSinks) && ...
            ~isempty(fieldnames(profile.commandSinks)), ...
            'Station:InvalidCatalog', 'Vehicle profile %s has no I/O candidates.', name);
        % ROS トピックの先頭グループが車両名と一致するか確かめる。
        candidates = [struct2cell(profile.odometrySources); ...
            struct2cell(profile.commandSinks)];
        for index = 1:numel(candidates)
            endpoint = candidates{index};
            if string(endpoint.protocol) ~= "ros", continue; end
            topic = string(endpoint.topic);
            expected = "/" + name + "/";
            assert(isscalar(topic) && startsWith(topic, expected) && ...
                strlength(topic) > strlength(expected), ...
                'Station:InvalidTopicGroup', ...
                'ROS topic %s for %s must start with %s.', topic, name, expected);
        end
        catalog.(fileName) = profile;
    end
end
